### ISSUE TITLE
todo: make this application fully functional

### ISSUE THREAD

**Issue by aishenreemo** [aishenreemo/tictactoe-rust#1]
- [ ] caching for performance
- [ ] make the user interact to the game
- [ ] make an A.I. using the [minimax](https://en.wikipedia.org/wiki/Minimax) algorithm
- [ ] Add delight to the experience when all tasks are complete :tada:

**Comment by aishenreemo** [comment]
ok im done for today bye
